### PR TITLE
Upgrade to manim 0.8.0

### PR DESCRIPTION
**Pull request by krashanoff**
Just wanted to update this program for folks to use with the latest version of manim.

Only relevant change between 0.4.0 and 0.8.0 that I could find is that `ShowCreation` was deprecated, and then deleted, in favor of `Create` in version 0.7.0 (see [here](https://docs.manim.community/en/stable/changelog/0.7.0-changelog.html#deprecated-classes-and-functions)). Updated the source and examples to reflect.

### CODE REVIEW

**Comment by mrdon** [comment]
Looks great, thanks! I think the version of manim also needs to be bumped, but I can do that

**Comment by mrdon** [comment]
Looks like the format build failed. Could you please bump setup.cfg at the same time?

**Comment by krashanoff** [comment]
I'll push the two requested changes in the next ~12 hours. Thanks for the quick reply!

**Comment by krashanoff** [comment]
Turned into a little more than I anticipated. There was a change in the manim CLI that I updated in the `Makefile`, and removal of certain properties from `Mobjects` like `font` in `VGroup`.

I updated the interface of this package so that it is backwards-compatible by taking the `font` property through relevant classes (see [widgets.py:L109](https://github.com/sleuth-io/code-video-generator/pull/4/files#diff-1a965416e9143a31f696846bd1e8143fac3dfd9c78bf812093aeb2f811106cd8R109)), or the `height` property in `ImageMobject` (see [scene.py:L142](https://github.com/sleuth-io/code-video-generator/pull/4/files#diff-67180141f89e88bbe8f03445543961582c866f77b172ad36a391ed13b2e51c6dL142)).

**Comment by mrdon** [comment]
I'm getting errors against 0.9  --dry_run invalid or some such

**Comment by krashanoff** [comment]
Apologies on the radio silence on this. I am currently in between an internship and the start of the academic year. The `--dry_run` option doesn't seem to work anymore as a flag or as a configuration option, which is strange. I documented it in an [issue on the ManimCommunity repo](https://github.com/ManimCommunity/manim/issues/1974). For now, removing the `--dry_run` option from the Docker tests *should* fix it. Was there a critical reason it was set?

**Pull request merged**
